### ISSUE TITLE
IL2CPP builds on Unity 2021.3.0 - Rider debugger broken

### ISSUE THREAD

**Issue by pistoleta** [JetBrains/resharper-unity#2304]
After upgrading Unity from 2020.3.30 to 2021.3.0 I see Rider is not able to debug on device anymore, I set breakpoint and Rider stops at the first one, but after that, either if I try to play continue or next but nothing happens, it looks like it continues on the Rider side but seems like its stuck permanently on that first breakpoint.

In Unity 2020.3.30 this works perfectly with the same project.

-Unity 2023..3.0
-Rider 2022.1
-MacOS 12.3.1 Monterey

**Comment by ahmetyazir22** [comment]
I also have the same problem with a similar setup on an Apple Silicon machine.  Mobile device freezes after hitting first breakpoint & step over etc does not work at all. Device becomes responsive only after unplugging it from the MacBook.

**Comment by citizenmatt** [comment]
Can you try the Early Access Preview builds of Rider 2022.2, please? This issue should be fixed

**Comment by vbandi** [comment]
@citizenmatt This also happens to me with Rider 2022.2.2 and building on Hololens. 

Additional info: After the first breakpoint is hit, any expression evaluations or just hovering the mouse over a variable also hangs the app on the device.

**Comment by pistoleta** [comment]
still happening
https://youtrack.jetbrains.com/issue/RIDER-82723/Debugger-breaks-and-game-freezes-for-IL2CPP-on-iOS-device

**Comment by pistoleta** [comment]
> I also have the same problem with a similar setup on an Apple Silicon machine. Mobile device freezes after hitting first breakpoint & step over etc does not work at all. Device becomes responsive only after unplugging it from the MacBook.

This is exactly my issue. Also using Apple Sillicon

**Comment by tachuscopely** [comment]
Any update on this? I have not been able to debug on device since upgrading to 2021. Also using apple silicon, Rider 2022.3.2 Build #RD-223.8617.53, built on January 25, 2023 MacOs Ventura 13.2 
Confirming Behaviour - 
Start app, connect via debugger on ip, hit breakpoint. Click next app hangs. It unfreezes when you kill the debugger

**Comment by pistoleta** [comment]
> Any update on this? I have not been able to debug on device since upgrading to 2021. Also using apple silicon, Rider 2022.3.2 Build #RD-223.8617.53, built on January 25, 2023 MacOs Ventura 13.2
> Confirming Behaviour -
> Start app, connect via debugger on ip, hit breakpoint. Click next app hangs. It unfreezes when you kill the debugger

Still happening

**Comment by pistoleta** [comment]
please people with this issue, make some noise here:

[https://youtrack.jetbrains.com/issue/RIDER-82723](url)

**Comment by citizenmatt** [comment]
Thanks for the link @pistoleta although something's gone wrong with copy/paste and it goes to GitHub issues. Here's the fixed link: [RIDER-82723](https://youtrack.jetbrains.com/issue/RIDER-82723)

There's also a (time-limited) private build available there to test a fix, which appears to be helping in many cases.
