### ISSUE TITLE
Methods used in Animation Events, show as "unused"

### ISSUE THREAD

**Issue by starr0stealer** [JetBrains/resharper-unity#488]
When wiring up `Animation Events` to call a `Scripts Method`, `Rider` displays these methods as `unused`.

Below is an image displaying the basic setup:

_The `GameObject: LevelComplete` has the `Script: LevelComplete.cs` attached to it. Then the `LevelComplete.anim` has an `Event` configured to call the `LevelComplete.LoadNextLevel` method._

_Note: In order to test this, the `Script` must be attached to the same `GameObject` as the `Animation`._

![Example Setup](https://i.imgur.com/1qa8feW.png)

Example Navigation path details (Scene.GameObject -> Script & -> AnimationController -> Animation -> Event).

_Within the `Scene` is a `GameObject` that has an `Animator` component, which references the `Animation Controller` file, and has a `MonoBehaviour` component, which references the C# file that contains the `Method` the `Animation Event` triggers._

_Then in the `Animation Controller` you find the `Animation(s)` via the `Animator State Machine`._

_Finally, in the `Animation` you can have `Events` that can call `Methods` from any `Script` attached to the same `GameObject` as the `Animation Controller`._

Scene source:
```yaml
--- !u!1 &405512269
GameObject:
  m_Component:
  - component: {fileID: 405512273}
  - component: {fileID: 405512274}
  m_Name: LevelComplete
--- !u!95 &405512273
Animator:
  m_GameObject: {fileID: 405512269}
  m_Controller: {fileID: 9100000, guid: 550ca101b7e507741b7d10d6ba8205db, type: 2}
--- !u!114 &405512274
MonoBehaviour:
  m_GameObject: {fileID: 405512269}
  m_Script: {fileID: 11500000, guid: bfaf5f13a5408ca44998ad75a16385fd, type: 3}
```

Animation Controller source:
```yaml
--- !u!91 &9100000
AnimatorController:
  m_Name: LevelComplete
  m_AnimatorLayers:
    m_StateMachine: {fileID: 1107805188659273550}
--- !u!1102 &1102957877984942184
AnimatorState:
  m_Name: LevelComplete
  m_Motion: {fileID: 7400000, guid: c559b4dac572ed548bc3d371da1dd836, type: 2}
--- !u!1107 &1107805188659273550
AnimatorStateMachine:
  m_ChildStates:
    m_State: {fileID: 1102957877984942184}
```

Animation source:
```yaml
--- !u!74 &7400000
AnimationClip:
  m_Name: LevelComplete
  m_Events:
    functionName: LoadNextLevel
```

Assumed logic to determine if a `Method` may be used by an `Animation Event`:
1. If `GameObject` has `Animator` and `MonoBehaviour` components
2. If `Animator -> Animation(s)` contains `Events`. _Loop on all `States` to check for `Events`_
3. If `Animation Event` function name(s) exist in the `Script` attached to the `GameObject`

_Note: It may be much easier to determine this, by just the method name, though Events can trigger Unity methods as well, so if those names are the same it would be false positives._

**Comment by citizenmatt** [comment]
We're looking at a solution, hopefully we can have something in place for Rider 2018.2

**Comment by citizenmatt** [comment]
Note that a workaround was added for 2018.2, which will mark any method or property that could be used as an event handler, or set by Unity as in use. This means any public static method or property setter in a Unity derived type. This is not very accurate, as it doesn't show if a method is actually being used, but is good enough to remove the false reports. This issue remains open to track a more accurate implementation.

**Comment by citizenmatt** [comment]
Now that YAML support is added:

* Add `.anim` to list of asset files being processed for references
* Add new references for `functionName` and `objectReferenceParameter` (method usage + class usage respectively)
* Add "Unity animation event handler" type for grouping in Find Usages

Example `.anim` file:

```yaml
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!74 &7400000
AnimationClip:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_Name: Level
  serializedVersion: 6
  m_Legacy: 0
  m_Compressed: 0
  m_UseHighQualityCurve: 1
  m_RotationCurves: []
  m_CompressedRotationCurves: []
  m_EulerCurves: []
  m_PositionCurves: []
  m_ScaleCurves: []
  m_FloatCurves: []
  m_PPtrCurves: []
  m_SampleRate: 60
  m_WrapMode: 0
  m_Bounds:
    m_Center: {x: 0, y: 0, z: 0}
    m_Extent: {x: 0, y: 0, z: 0}
  m_ClipBindingConstant:
    genericBindings: []
    pptrCurveMapping: []
  m_AnimationClipSettings:
    serializedVersion: 2
    m_AdditiveReferencePoseClip: {fileID: 0}
    m_AdditiveReferencePoseTime: 0
    m_StartTime: 0
    m_StopTime: 0
    m_OrientationOffsetY: 0
    m_Level: 0
    m_CycleOffset: 0
    m_HasAdditiveReferencePose: 0
    m_LoopTime: 1
    m_LoopBlend: 0
    m_LoopBlendOrientation: 0
    m_LoopBlendPositionY: 0
    m_LoopBlendPositionXZ: 0
    m_KeepOriginalOrientation: 0
    m_KeepOriginalPositionY: 1
    m_KeepOriginalPositionXZ: 0
    m_HeightFromFeet: 0
    m_Mirror: 0
  m_EditorCurves: []
  m_EulerEditorCurves: []
  m_HasGenericRootTransform: 0
  m_HasMotionFloatCurves: 0
  m_GenerateMotionCurves: 0
  m_Events:
  - time: 0
    functionName: LoadNextLevel
    data: 
    objectReferenceParameter: {fileID: 11500000, guid: 8b3afbb5c1774f8680bd0071afe5267f,
      type: 3}
    floatParameter: 0
    intParameter: 0
    messageOptions: 0
```

**Comment by ManuelRauber** [comment]
@citizenmatt When this is fixed, will this also fix normal Unity Event Handlers? e.g. I've a script with `public void HandleClick()`. This method is than used in a Button Click Handler (set via Inspector UI). Rider marks this as unused as well.

**Comment by citizenmatt** [comment]
Standard event handlers should already work. What Rider version are you using, and what file is the handler being referenced from (scene, prefab, etc.)?

**Comment by diegoadrada** [comment]
Any news about when this is going to be fixed? I'm using Rider 2019.3

**Comment by Gazoon007** [comment]
Any updates?

**Comment by sal48** [comment]
Looks like this is still an open ticket. As a sloppy workaround, I denote animation events in a region, but it would be great if Rider can show the anims to which they belong.

**Comment by MToolmaker** [comment]
Hey folk! It's implemented and it will be available in the closest Rider 2021.1 EAP. Here are all implemented functionality:
https://youtrack.jetbrains.com/issue/RIDER-43464
https://youtrack.jetbrains.com/issue/RIDER-43338
https://youtrack.jetbrains.com/issue/RIDER-17449
PR: https://github.com/JetBrains/resharper-unity/pull/1982

**Comment by dogukankse** [comment]
I'm using 2021.3.2 and this issue still exists.

**Comment by citizenmatt** [comment]
Sorry, the notes in that comment were implementation details, not end user instructions. [Ivan's comment above](https://github.com/JetBrains/resharper-unity/issues/488#issuecomment-760221355) states that this has been fixed in Rider 2022.1. Have you tried the latest EAP?

**Comment by innoriguaman** [comment]
Hi, I have just installed this version of Rider

![image](https://user-images.githubusercontent.com/99425306/153569847-38985ba7-46bb-4940-9070-619b15bd8cc5.png)

but it is still showing the mehtod as unused

**Comment by leohilbert** [comment]
Hi, @citizenmatt thanks for looking into that! :) I'm experiencing the same problem.
In the comment above "2021.1 EAP" was mentioned, not 2022. That's why I thought it should already be part of the current Rider-Release. I checked at 2022.1 EAP as well now, but the issue is still present :(

**Comment by citizenmatt** [comment]
Yeah, I totally misread that, sorry! 😊  I need to take another look at this and see what's going on. Can I just confirm that you're seeing methods that are marked unused, but they are in use, in a `.anim` file? I forget details, aren't there a couple of different animation files?

**Comment by leohilbert** [comment]
![Screenshot 2022-02-11 132011](https://user-images.githubusercontent.com/2004063/153590442-d0e97e7d-4d7e-466a-834f-296fb7470f50.png)
![Screenshot 2022-02-11 131943](https://user-images.githubusercontent.com/2004063/153590445-dff2a413-dbcd-4225-a50e-8c427b84b874.png)

😸

**Comment by citizenmatt** [comment]
Thanks both, I'll investigate further

**Comment by leohilbert** [comment]
@citizenmatt did you find the time to look into this? :) Still reproducible for me. Currently adding `[UsedImplicitly]` as a workaround, but a working detection would be nice. Maybe the issue can be reopened?

**Comment by gustavopsantos** [comment]
@citizenmatt Also you need to scan for .meta files. For instance .fbx can have baked animation clips inside it containing events.
![image](https://user-images.githubusercontent.com/27857857/195879752-be8cb9b0-7de0-4a19-9021-1dda587fa00a.png)

**Comment by van800** [comment]
Similar to https://youtrack.jetbrains.com/issue/RIDER-77030/Methods-referenced-by-Unity-Animation-Events-are-shown-as-unused

**Comment by nstdspace** [comment]
This is not implemented yet, is it? Why is the issue marked as closed?

**Comment by van800** [comment]
There are 2 types of animation events. One of them is supported, the other is in the works, hopefully for 23.1. please follow https://youtrack.jetbrains.com/issue/RIDER-77030/Methods-referenced-by-Unity-Animation-Events-are-shown-as-unused
